version: '3'

services:
  tomcat:
    build: tomcat
    image: tomcatimage:1.0
    ports: 
      - 8080:8080
    networks:
      - webstack
    container_name: tomcatcomp

  db:
#    env_file:
#      - .env
    build: 
      context: db
      args:
        - db_root_pass=${db_root_pass}
        - db_pass={db_pass}
    image: dbimage:1.0s
    # environment:
    #   - db_root_pass=${db_root_pass}
    #   - db_pass=${db_pass}
    networks:
      - webstack
    container_name: dbcomp

networks:
  webstack:
    driver: bridge