version: '3'

services:
  tomcat:
    build: tomcat
    image: tomcatimage:1.0
    ports: 
      - 8080:8080
    networks:
      - webstack
    container_name: tomcatcomp

  db:
    build: 
      context: db
      args:
        - db_root_pass=admin123
        - db_pass=todo123
    image: dbimage:1.0s
    networks:
      - webstack
    container_name: dbcomp

networks:
  webstack:
    driver: bridge