FROM centos:7

RUN yum update -y && \
    yum install http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm -y && \
    yum install mysql-server -y && \
    yum clean all && \
    rm -rf /var/cache/yum

USER mysql

#the prescript below creates the SQL structure - needed to create the system tables
RUN /usr/bin/mysql-systemd-start pre

EXPOSE 3306

#Copies the SQL scripts over to the images from the local machine
COPY db_install.sql db_install.sql
COPY db_setup.sql db_setup.sql

#declare variables
ARG db_root_pass
ARG db_name=tododb
ARG db_user=todo
ARG db_pass

#sets the root password to whatever the value was when the container was run
#runs the db_install sql script to 

#this is boots up mysql - basedir is where all the files are created
#CMD mysqld
#/usr/bin/mysqld_safe --basedir=/usr
#USER root
RUN eval "/usr/bin/mysqld_safe &" && \
    /usr/bin/mysql-systemd-start post && \
    mysql --user=root -e "\
        set @root_pass='$db_root_pass'; \
        source db_install.sql; \
    " && \
    mysql --user=root --password=${db_root_pass} -e "\
        set @db_name='${db_name}';\
        set @db_user='${db_user}';\
        set @db_pass='${db_pass}';\
        source db_setup.sql;\
    " && \
    /usr/bin/mysqladmin -uroot --password=${db_root_pass} shutdown

USER mysql
CMD /usr/bin/mysqld_safe
